/**
 * Example: Extract JSON Resume from PDF
 */
import { extractResumeFromFile, hasResumeMetadata } from "./src/index";
import { join } from "path";

console.log("╔══════════════════════════════════════════════════════════════╗");
console.log("║          PDF Resume Metadata Extractor - Example            ║");
console.log("╚══════════════════════════════════════════════════════════════╝\n");

// Path to a PDF file with embedded resume
const pdfPath = join(__dirname, "../../resumes/example_output.pdf");

console.log(`📄 Extracting resume from: ${pdfPath}\n`);

const result = await extractResumeFromFile(pdfPath);

if (result.success && result.resume) {
  console.log("✅ Successfully extracted JSON Resume!\n");
  
  console.log("Resume Data:");
  console.log("═".repeat(60));
  
  if (result.resume.basics) {
    console.log(`Name:     ${result.resume.basics.name || 'N/A'}`);
    console.log(`Label:    ${result.resume.basics.label || 'N/A'}`);
    console.log(`Email:    ${result.resume.basics.email || 'N/A'}`);
    console.log(`Phone:    ${result.resume.basics.phone || 'N/A'}`);
    console.log(`Website:  ${result.resume.basics.url || 'N/A'}`);
    
    if (result.resume.basics.location) {
      console.log(`Location: ${result.resume.basics.location.city || ''}, ${result.resume.basics.location.countryCode || ''}`);
    }
  }
  
  console.log();
  
  if (result.resume.work && result.resume.work.length > 0) {
    console.log(`Work Experience: ${result.resume.work.length} entries`);
    result.resume.work.forEach((job, index) => {
      console.log(`  ${index + 1}. ${job.position || 'N/A'} at ${job.name || 'N/A'}`);
      console.log(`     ${job.startDate || ''} - ${job.endDate || 'Present'}`);
    });
    console.log();
  }
  
  if (result.resume.education && result.resume.education.length > 0) {
    console.log(`Education: ${result.resume.education.length} entries`);
    result.resume.education.forEach((edu, index) => {
      console.log(`  ${index + 1}. ${edu.studyType || ''} in ${edu.area || 'N/A'}`);
      console.log(`     ${edu.institution || 'N/A'}`);
    });
    console.log();
  }
  
  if (result.resume.skills && result.resume.skills.length > 0) {
    console.log(`Skills: ${result.resume.skills.length} categories`);
    result.resume.skills.forEach((skill) => {
      console.log(`  • ${skill.name}: ${skill.keywords?.join(', ') || ''}`);
    });
    console.log();
  }
  
  // Save extracted resume to a file
  const outputPath = join(__dirname, "../../resumes/extracted_resume.json");
  await Bun.write(outputPath, JSON.stringify(result.resume, null, 2));
  console.log(`💾 Saved extracted resume to: ${outputPath}`);
  
} else {
  console.log(`❌ Failed to extract resume: ${result.error}`);
  console.log();
  console.log("Make sure the PDF file:");
  console.log("  1. Exists at the specified path");
  console.log("  2. Was generated by flouka-studio (contains embedded resume.json)");
  console.log();
  console.log("Try generating a PDF first:");
  console.log("  bun run flouka:example");
}

console.log();
console.log("╔══════════════════════════════════════════════════════════════╗");
console.log("║                    Extraction Complete!                      ║");
console.log("╚══════════════════════════════════════════════════════════════╝");
